### ISSUE TITLE
[1.] Make tasks work offline and create-if-not-exists based on taskName on server.

### ISSUE THREAD

**Issue by accolasia** [openmastery/plugins#19]
The taskId thing is irritating as hell and super brittle.

Once again, my batches are stuck in queue and not going to the server.

com.bancvue.rest.exception.NotFoundException: {"timestamp":1482624415357,"status":404,"error":"Not Found","message":"Not Found","path":"/ideaflow/collect/batch"}
	at com.bancvue.rest.exception.DefaultWebApplicationExceptionFactory.createException(DefaultWebApplicationExceptionFactory.java:38)
	at com.bancvue.rest.client.response.CreateResponse.doGetValidatedResponse(CreateResponse.java:36)
	at com.bancvue.rest.client.response.AbstractResponse.getValidatedResponseAndCloseClientResponse(AbstractResponse.java:48)
	at com.bancvue.rest.client.response.AbstractResponse.getValidatedResponse(AbstractResponse.java:43)
	at com.bancvue.rest.client.crud.CrudClientRequest.createWithPost(CrudClientRequest.java:176)
	at org.openmastery.publisher.client.BatchClient.addIFMBatch(BatchClient.java:22)
	at org.openmastery.publisher.client.BatchClient$addIFMBatch.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.ideaflow.activity.BatchPublisher.publishBatch(BatchPublisher.groovy:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:361)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:877)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at com.ideaflow.activity.BatchPublisher$_publishBatches_closure1.doCall(BatchPublisher.groovy:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:877)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:425)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1376)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1348)
	at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.ideaflow.activity.BatchPublisher.publishBatches(BatchPublisher.groovy:71)
	at com.ideaflow.activity.BatchPublisher$publishBatches.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
	at com.ideaflow.activity.BatchPublisher.run(BatchPublisher.groovy:49)
	at java.lang.Thread.run(Thread.java:695)

**Comment by mlueders** [comment]
will not fix - instead, will isolate all task activity to individual files so if a batch fails due to missing task while pointing to one server, other batches will not be affected and the failing batches should resume when connected to the declaring server.  the general case for multiple servers is tooling development.
